name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v3.1.1
        with:
          node-version: 16.x
      - name: Restore cache
        uses: actions/cache@v3.2.4
        with:
          path: common/temp/pnpm-store
          key: ${{ runner.os }}-{{ hashFiles('common/config/rush/pnpm-lock.yaml') }}
      - name: Assert dependency versions
        run: node common/scripts/install-run-rush.js check
      - name: Assert Changelogs
        run: node common/scripts/install-run-rush.js change --verify
  test-nest-cqrs:
    needs: verify
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        package: [core, eventstoredb, 'nats']
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3.1.1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Restore cache
        uses: actions/cache@v3.2.4
        with:
          path: common/temp/pnpm-store
          key: ${{ runner.os }}-{{ hashFiles('common/config/rush/pnpm-lock.yaml') }}
      - name: Rush Install
        run: node common/scripts/install-run-rush.js install
      - name: Build
        run: | 
          node common/scripts/install-run-rush.js build -T @nest-cqrs/${{ matrix.package }}
      - name: Test
        run: | 
          npm run test --prefix packages/${{ matrix.package }}
  publsh:
    runs-on: ubuntu-latest
    needs: [verify]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3.1.1
        with:
          node-version: 20.x
      - name: Restore cache
        uses: actions/cache@v3.2.4
        with:
          path: common/temp/pnpm-store
          key: ${{ runner.os }}-{{ hashFiles('common/config/rush/pnpm-lock.yaml') }}
      - name: Rush Install
        run: node common/scripts/install-run-rush.js install
      - name: Rush Build
        run: node common/scripts/install-run-rush.js build
      - name: Publish
        run: node common/scripts/install-run-rush.js publish --publish -n ${{ secrets.NPM_TOKEN }} --include-all --set-access-level public
